import { Button, Card, Divider, Form, Input, Modal, Select } from 'antd'
import Meta from 'antd/lib/card/Meta';
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react';

const Home: NextPage = ({ companies, availableLinks }: any) => {
  const [isLinksModalVisible, setIsModalLinksVisible] = useState(false)
  const [selectedCompany, setSelectedCompany] = useState(companies[0])

  const hideLinksModal = () => setIsModalLinksVisible(false)
  const showLinksModal = () => setIsModalLinksVisible(true)

  return (
    <div>
      <Head>
        <title>Qual é o link ?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Form
          style={{ width: "50vw" }}
          layout="vertical"
          name="basic"
          initialValues={{ remember: true }}
          onFinish={showLinksModal}
          autoComplete="off"
        >
          <Form.Item name="company" label="Empresa" style={{ minWidth: "100%"}}>
            <Input.Group>
              <Select 
                allowClear 
                placeholder="Selecione a empresa"
                value={selectedCompany}
                onChange={setSelectedCompany}
                defaultActiveFirstOption
                style={{ minWidth: "70%" }}
              >
                {companies.map((companyItem: any) => 
                  <Select.Option key={companyItem}>
                    {companyItem}
                  </Select.Option>
                )}
              </Select>
              <Button type="primary" htmlType="submit" style={{ width: "30%" }}>
                Buscar links
              </Button>
            </Input.Group>
          </Form.Item>              
        </Form>

        <div>
          {
            isLinksModalVisible && (
              <>
                <Divider orientation='left'>Chamados</Divider>
                <div
                  style={{
                    display: "grid",
                    gridTemplateColumns: "repeat(3, 1fr)",
                    columnGap: "12px",
                    minWidth: "100%",
                  }}
                >
                  {
                    [
                      {
                        label: "Help Desk",
                        img: "",
                        url: "http://chamadosti.poptrade.com.br/redmine/login",
                      },
                      {
                        label: "SRC",
                        img: "",
                        url: "https://src.softtrade.com.br/",
                      },
                      {
                        label: "SRC",
                        img: "",
                        url: "https://www.locaweb.com.br/",
                      },
                    ].map((item: any, index: any) => {
                      return (
                        <Card
                          size="small"
                          hoverable
                          style={{ width: 240 }}
                          key={index}
                          actions={[<a key={index} href={item.url} target="__blank">Acessar</a>]}
                        >
                          <Meta title={item.label} description={item.url} />
                        </Card>
                      )
                    })
                  }
                </div>
              </>
            )
          }
        </div>
    </div>
  )
}

export async function getServerSideProps(ctx: any) {
  const companyOptions = [ "Seven","Pop","GTrademark" ];

  const linkOptions = {
    "chamados": [
      {
        label: "Help Desk",
        img: "",
      },
      {
        label: "SRC",
        img: "",
      },
      {
        label: "SRC",
        img: "",
      },
    ],
    "webmail": [
      {
        label: "@seventrademkt",
        img: "",
      },
      {
        label: "@seventradesys",
        img: "",
      },
    ],
    "gestão de pessoas": [
      {
        label: "Fator",
        img: "",
      },
      {
        label: "Tradeview",
        img: "",
      },
      {
        label: "Agile",
        img: "",
      },
      {
        label: "BI",
        img: "",
      },
      {
        label: "Tangerino",
        img: "",
      },
    ],
    "controle": [
      {
        label: "Gestão de Ativos",
        img: "",
      },
      {
        label: "Holmes",
        img: "",
      },
    ],
    "intranet": [
      {
        label: "Seven",
        img: "",
      },
    ],
  }

  return {
    props: {
      companies: companyOptions,
      availableLinks: linkOptions,
    }
  }
}

export default Home;
